### PR TITLE
Conversion of App to Kotlin 👌 (Kotlinification)

### PR DESCRIPTION
**Pull request by etonotieno**
This PR converts the entire codebase to Kotlin and also fixes some of the UI bugs like overlapping of the text in the Recycler View. I am also planning to incorporate an architecture to showcase some best practices of making an app and also how to use the LNM api. @jumaallan @TheDancerCodes @kioko Any ideas to make this better is welcome.

### CODE REVIEW

**Comment by jumaallan** [comment]
@CodeZilla7 

From what @kioko explained, they wanted to make it easy for beginners to understand how LNM works. The best way to handle your PR is forking it from your repo, as a Kotlin Sample. This will make sure the Java Sample still remains available to the `Java-rians` 🚀

**Comment by etonotieno** [comment]
That's actually a good idea. They can fork the Kotlin version that also shows some best practices to follow when creating your app. Something that's not hard to understand but also very useful especially to more experienced devs.

**Comment by jumaallan** [comment]
Yes, that would be the best way to handle it. I could help fork the repo once it's done

**Comment by kisese** [comment]
The main aim of these repos is to show how to use the APIs in  as many languages as possible, so it would be best to do kotlin in a new repo so we keep java, as long as you maintain the same UX flow, keep the code easy to understand for all levels of developers and prioritise how to use the API

**Pull request closed without merging**
